[package]
name = "gui_app"
version = "0.1.0"
edition = "2021"

[dependencies]
app = { version = "0.1.0", path = "../../crates/app" }
futures = "0.3.28"
reqwest = "0.11.22"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.33.0", features = ["full"] }
tvdb = { version = "0.1.0", path = "../../crates/tvdb" }
eframe = { version = "0.23.0", features = ["persistence"] }
egui = { version = "0.23.0", features = ["persistence"] }
egui_extras = { version = "0.23.0" }
open = "5.0.0"
serde_with = "3.4.0"
enum-map = "2.7.0"
lazy_static = "1.4.0"

