[package]
name = "gui_app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
app = { version = "0.1.0", path = "../../crates/app" }
reqwest = "0.11.22"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.33.0", features = ["full"] }
tvdb = { version = "0.1.0", path = "../../crates/tvdb" }

