[package]
name = "tvdb"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
reqwest = "0.11.22"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = { version = "1.0.107", features = ["raw_value"] }
serde_with = "3.4.0"
thiserror = "1.0.50"
url = "2.4.1"
